@baseUrl = http://localhost:5000

@urlPath = api/v1

POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true


{
     "username": "danny",
     "password": "qwerty",
      "email": "dan@test.com",
      "avatarColor": "red",
      "avatarImage": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/AAAfwD+Qm6iHwAAAABJRU5ErkJggg=="



}